@baseUrl = http://localhost:3000
@token =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhdXRoMCIsImVtYWlsIjoiYWRtaW5AdmluY2kuYmUiLCJpYXQiOjE3NzYyNjE0MTAsImV4cCI6MTc3NjM0NzgxMH0.MNe_6LFMEln4nIFgq9GR7UH0FUGIBGm76vjSg45CmQ8


### LOGIN ADMIN
### -------------------------------------------
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "email": "admin@vinci.be",
  "password": "admin"
}


### Encode a match result - success (should return 200)
PATCH {{baseUrl}}/matches/1/result
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "scoreA": 3,
  "scoreB": 1
}

### Encode a match result - match not found (should return 404)
PATCH {{baseUrl}}/matches/999/result
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "scoreA": 3,
  "scoreB": 1
}

### Encode a match result - draw score (should return 400)
PATCH {{baseUrl}}/matches/1/result
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "scoreA": 2,
  "scoreB": 2
}

### Encode a match result - score <= 0 (should return 400)
PATCH {{baseUrl}}/matches/1/result
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "scoreA": 0,
  "scoreB": 3
}

### Encode a match result - already encoded (should return 400)
PATCH {{baseUrl}}/matches/2/result
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "scoreA": 3,
  "scoreB": 1
}

### Encode a match result - match canceled or forfeit (should return 400)
PATCH {{baseUrl}}/matches/3/result
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "scoreA": 3,
  "scoreB": 1
}

### Encode a match result - unauthorized (no token) (should return 403)
PATCH {{baseUrl}}/matches/1/result
Content-Type: application/json

{
  "scoreA": 3,
  "scoreB": 1
}