@baseUrl = http://localhost:3000
@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhdXRoMCIsImVtYWlsIjoiYWRtaW5AdmluY2kuYmUiLCJpYXQiOjE3NzMzNDA3OTEsImV4cCI6MTc3MzQyNzE5MX0.ohi086Zp3f3lEEVEx9RnexG-lyAUsLCldK5di8hK7BE
@memberToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhdXRoMCIsImVtYWlsIjoibGVhQG1haWwuY29tIiwiaWF0IjoxNzczMzQwMjE0LCJleHAiOjE3NzM0MjY2MTR9.bwGiqltccvtqpksbhxPDk4UYjM5hUB3lmKUYxNWiTJM
@nonExistentMemberId = 999
@existingMemberId = 2


### 3. Login admin (CommandLineRunner)
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "email": "admin@vinci.be",
  "password": "admin"
}

### 2. Login new member (200 + Token)
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "email": "lea@mail.com",
  "password": "lea"
}

### 1. Promote member 2 (success) → devient admin
PUT {{baseUrl}}/members/admins/{{existingMemberId}}
Authorization: Bearer {{adminToken}}

### 2. Promote member 2 encore (déjà admin → 400)
PUT {{baseUrl}}/members/admins/{{existingMemberId}}
Authorization: Bearer {{adminToken}}

### 3. Promote avec token non-admin (→ 403)
PUT {{baseUrl}}/members/admins/{{existingMemberId}}
Authorization: Bearer {{memberToken}}

### 4. Promote membre inexistant (→ 400)
PUT {{baseUrl}}/members/admins/{{nonExistentMemberId}}
Authorization: Bearer {{adminToken}}

### 5. Demote avec token non-admin (→ 403)
DELETE {{baseUrl}}/members/admins/{{existingMemberId}}
Authorization: Bearer {{memberToken}}

### 6. Demote last admin ID 1 (→ 400)
DELETE {{baseUrl}}/members/admins/1
Authorization: Bearer {{adminToken}}

### 7. Demote member 2 (success) → redevient membre
DELETE {{baseUrl}}/members/admins/{{existingMemberId}}
Authorization: Bearer {{adminToken}}

### 8. Demote member 2 encore (pas admin → 400)
DELETE {{baseUrl}}/members/admins/{{existingMemberId}}
Authorization: Bearer {{adminToken}}


### Get all admins
GET {{baseUrl}}/members/admins
Authorization: Bearer {{adminToken}}