@baseUrl = http://localhost:5433

### 1. Try to login an unknown user
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "email": "unknown@vinci.be",
  "password": "admin"
}

### 2. Register a new member
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
  "email": "joueur1@vinci.be",
  "password": "password123",
  "tag": "Ninja#001",
  "imageId": 1,
  "specialityId": 1
}

### 3. Login the new member
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "email": "joueur1@vinci.be",
  "password": "password123"
}

> {% client.global.set("token", response.body.token) %}

### 4. Auto-Login
GET {{baseUrl}}/auths/me
Authorization: Bearer {{token}}

### 5. Try to access a secure route without token
GET {{baseUrl}}/auths/me
