@baseUrl = http://localhost:3000

### TESTS SCENARIO
### THE OBJECTIVE IS TO TEST THE API SECURITY

### 0. Tokens
@userToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhdXRoMCIsImVtYWlsIjoibmV3QHZpbmNpLmJlIiwiaWF0IjoxNzcyODM2NDMwLCJleHAiOjE3NzI5MjI4MzB9.hOFxWtso3qoUXrOGWXWM8smSKO8_Va7fd2jIQFT_FvA
@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhdXRoMCIsImVtYWlsIjoiYWRtaW5AdmluY2kuYmUiLCJpYXQiOjE3NzMyNDEyNDksImV4cCI6MTc3MzMyNzY0OX0.KOt29e-Z4ahaT4TfER0KdB5jRsZ0gbAjh2M8R4nMmwo

### REGISTER & LOGIN (ok)
### 1. Valid new member registration (201)
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
  "email": "sanstoken@vinci.be",
  "password": "sanstoken",
  "tag": "New",
  "imageId": 1,
  "specialityId": 1
}

### 2. Login new member (200 + Token)
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "email": "sanstoken@vinci.be",
  "password": "sanstoken"
}

### 3. Login admin (CommandLineRunner)
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "email": "admin@vinci.be",
  "password": "admin"
}

### TOKENS (ko)
### 1. Protected route without token
GET {{baseUrl}}/auths/me

### 2. Protected route with fake token
GET {{baseUrl}}/auths/me
Authorization: Bearer fake.token

### ROLES: (isAuthenticated vs hasRole) (ok)
### 1. Logged member acces to /me (200 + new token)
GET {{baseUrl}}/auths/me
Authorization: Bearer {{userToken}}

### 2. Logged admin acces to /me (200 + new token)
GET {{baseUrl}}/auths/me
Authorization: Bearer {{adminToken}}

### ADMIN ONLY (ko)
### 1. Member try to do an admin only action (403)
#DELETE/GET/UPDATE/CREATE {{baseUrl}}/xxx/xxx
Authorization: Bearer {{userToken}}

### 2. Admin try to do an admin only action (200)
#DELETE/GET/UPDATE/CREATE {{baseUrl}}/xxx/xxx
Authorization: Bearer {{adminToken}}
