@baseUrl = http://localhost:3000
@adminToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhdXRoMCIsImVtYWlsIjoiYWRtaW5AdmluY2kuYmUiLCJpYXQiOjE3NzY3MDUxODEsImV4cCI6MTc3Njc5MTU4MX0.okWpfOcvA0zu9YymPQPiDlvmTPprv8ruiO3b0Q9XlgU
@userToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhdXRoMCIsImVtYWlsIjoibGVhQG1haWwuY29tIiwiaWF0IjoxNzc0NzA3MDg5LCJleHAiOjE3NzQ3OTM0ODl9.uQZzEgY2p3yHs2Vr5TAJEbPKqpwD8WebtF2OrJY6StY


## Login as an admin to get the token (user already in db)
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "email": "admin@vinci.be",
  "password": "admin"
}


### Bannish a member (OK - 200)
POST {{baseUrl}}/admin/banishments/2
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "reason": "Triche détéctée"
}


### Bannish a member who is already banned (KO - 409 Conflict)
POST {{baseUrl}}/admin/banishments/7
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "reason": "Triche détéctée"
}


### Bannish a non-existing member (KO - 404 Not found)
POST {{baseUrl}}/admin/banishments/18637
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "reason": "Unexisting"
}


### Login as a user to get the token (user already in db)
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "email": "lea@mail.com",
  "password": "lea"
}


### Try to ban a member as a non-admin user (KO - 403 Forbidden)
POST {{baseUrl}}/admin/banishments/2
Authorization: Bearer {{userToken}}
Content-Type: application/json

{
  "reason": "I am not an admin"
}


### Try to ban the responsible of TEAM_IOTA (OK - the second responsible becomes the new responsible)
POST {{baseUrl}}/admin/banishments/8
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "reason": "Test ban responsable"
}

### Try to ban the responsible of TEAM_ALPHA (OK - the oldest member become the new responsible)
POST {{baseUrl}}/admin/banishments/1
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "reason": "Test ban responsable"
}
