@baseUrl = http://localhost:3000
@token = <ton_token>

### Approve a request (should return 204)
PATCH {{baseUrl}}/membership-requests/1/approve
Authorization: Bearer {{token}}

### Approve a request not found (should return 404)
PATCH {{baseUrl}}/membership-requests/999/approve
Authorization: Bearer {{token}}

### Refuse a request (should return 204)
PATCH {{baseUrl}}/membership-requests/1/refuse
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "reason": "Not a good fit"
}

### Refuse a request not found (should return 404)
PATCH {{baseUrl}}/membership-requests/999/refuse
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "reason": "Not a good fit"
}