@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhdXRoMCIsImVtYWlsIjoibmV3QHZpbmNpLmJlIiwiaWF0IjoxNzcyOTk2NzUxLCJleHAiOjE3NzMwODMxNTF9.1eAfOvCxkLUT7khqPIMmwofjyUw5wXTPSIRlAalzSdo

### Get my profile
GET {{baseUrl}}/members/me
Authorization: Bearer {{token}}

### Update my profile
PATCH {{baseUrl}}/members/me
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "speciality": "Tacticien",
  "profileImage": "img3.png"
}

### Change password (OK)
PATCH {{baseUrl}}/members/change-password
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "oldPassword": "new",
  "newPassword": "newPswd2026"
}

### Change password (KO - Wrong old password)
PATCH {{baseUrl}}/members/change-password
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "oldPassword": "old",
  "newPassword": "newPswd2026"
}