@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhdXRoMCIsImVtYWlsIjoiYWRtaW5AdmluY2kuYmUiLCJpYXQiOjE3NzQ4MDQzMTgsImV4cCI6MTc3NDg5MDcxOH0.rzHwO44LoESe_OXVzwieX3goW1oQuaQgbFrk2DNpavc

### Get my profile
GET {{baseUrl}}/members/me
Authorization: Bearer {{token}}

### Update my profile
PATCH {{baseUrl}}/members/me
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "speciality": "tacticien",
  "profileImage": "img3.png"
}

### Change password (KO - Wrong old password)
PATCH {{baseUrl}}/members/password
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "oldPassword": "old",
  "newPassword": "newPswd2026",
  "confirmPassword": "newPswd2026"
}

### Change password (KO - Wrong confirmation password)
PATCH {{baseUrl}}/members/password
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "oldPassword": "new",
  "newPassword": "newPswd2026",
  "confirmPassword": "newPswd"
}

### Change password (KO - New password same as the previous)
PATCH {{baseUrl}}/members/password
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "oldPassword": "new",
  "newPassword": "new",
  "confirmPassword": "new"
}

### Change password (KO - Too short)
PATCH {{baseUrl}}/members/password
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "oldPassword": "luffy",
  "newPassword": "Abc1!",
  "confirmPassword": "Abc1!"
}

### Change password (KO - Missing uppercase)
PATCH {{baseUrl}}/members/password
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "oldPassword": "luffy",
  "newPassword": "vinci123!",
  "confirmPassword": "vinci123!"
}

### Change password (KO - Missing number)
PATCH {{baseUrl}}/members/password
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "oldPassword": "luffy",
  "newPassword": "LeoVinci!",
  "confirmPassword": "LeoVinci!"
}

### Change password (KO - Missing special character)
PATCH {{baseUrl}}/members/password
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "oldPassword": "new",
  "newPassword": "LeoVinci12",
  "confirmPassword": "LeoVinci12"
}

### Change password (OK)
PATCH {{baseUrl}}/members/password
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "oldPassword": "luffy",
  "newPassword": "LeoVinci123!",
  "confirmPassword": "LeoVinci123!"
}

### Get a member public profile (OK - Existing ID)
GET {{baseUrl}}/members/1
Authorization: Bearer {{token}}

### Get a member public profile (KO - Non-existing ID)
GET {{baseUrl}}/members/9999999

### Get a member public profile (OK - (without Token))
GET {{baseUrl}}/members/2



