@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhdXRoMCIsImVtYWlsIjoibGVhQG1haWwuY29tIiwiaWF0IjoxNzczMzM0MDY3LCJleHAiOjE3NzM0MjA0Njd9.d9T21ZaX6oc7pT7TUkJVE0gi6Vb5mzm0fMMwk9AJGzw
### Get my profile
GET {{baseUrl}}/members/me
Authorization: Bearer {{token}}

### Update my profile
PATCH {{baseUrl}}/members/me
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "speciality": "tacticien",
  "profileImage": "img3.png"
}

### Change password (OK)
PATCH {{baseUrl}}/members/password
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "oldPassword": "new",
  "newPassword": "newPswd2026",
  "confirmPassword": "newPswd2026"
}

### Change password (KO - Wrong old password)
PATCH {{baseUrl}}/members/password
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "oldPassword": "old",
  "newPassword": "newPswd2026",
  "confirmPassword": "newPswd2026"
}

### Change password (KO - Wrong confirmation password)
PATCH {{baseUrl}}/members/password
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "oldPassword": "new",
  "newPassword": "newPswd2026",
  "confirmPassword": "newPswd"
}

### Change password (KO - New password same as the previous)
PATCH {{baseUrl}}/members/password
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "oldPassword": "new",
  "newPassword": "new",
  "confirmPassword": "new"
}