### Set base URL
@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhdXRoMCIsImVtYWlsIjoicmVzcG9uc2libGVAdmluY2kuYmUiLCJpYXQiOjE3NzMxMzI1NTksImV4cCI6MTc3MzIxODk1OX0.H2P2HfJJeiYMXXi14976vecZ34LlGQ6eNzahmq0jghs
@token2 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhdXRoMCIsImVtYWlsIjoibWVtYmVyQHZpbmNpLmJlIiwiaWF0IjoxNzczMTMyNTgwLCJleHAiOjE3NzMyMTg5ODB9.5Ul16SjjKfmfJC84ypGMtKMycEkxMCOgVYu3tr5EaxU

### Register responsible member
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
  "email": "responsible@vinci.be",
  "password": "test123",
  "tag": "Responsible",
  "imageId": 1,
  "specialityId": 1
}

### Register regular member
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
  "email": "member@vinci.be",
  "password": "test123",
  "tag": "Member",
  "imageId": 1,
  "specialityId": 1
}

### Login responsible (copy token into @token)
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "email": "responsible@vinci.be",
  "password": "test123"
}

### Login regular member (copy token into @token2)
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "email": "member@vinci.be",
  "password": "test123"
}

### Create a team with responsible (should return 201)
POST {{baseUrl}}/teams
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "TeamTest"
}

### Create membership request from member (should return 201 + notif sent to responsible)
POST {{baseUrl}}/teams/1/membership-requests
Authorization: Bearer {{token2}}

### Check notifications of responsible (should contain membership request notif)
GET {{baseUrl}}/members/3/notifications
Authorization: Bearer {{token}}

### Try to create membership request for non-existent team (should return 404)
POST {{baseUrl}}/teams/999/membership-requests
Authorization: Bearer {{token2}}

### Try to create membership request without token (should return 403)
POST {{baseUrl}}/teams/1/membership-requests