### Set base URL
@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhdXRoMCIsImVtYWlsIjoidGVzdEB2aW5jaS5iZSIsImlhdCI6MTc3Mjk5NDc2NCwiZXhwIjoxNzczMDgxMTY0fQ.qAvTNTAff6empfV4XvVBdxYbweGWU9aWLSGPYk8FN98
@token2 =

### Register a member
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
  "email": "test@vinci.be",
  "password": "test123",
  "tag": "TestUser",
  "imageId": 1,
  "specialityId": 1
}

### Register a second member
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
  "email": "test2@vinci.be",
  "password": "test123",
  "tag": "TestUser2",
  "imageId": 1,
  "specialityId": 1
}

### Login member 1
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "email": "test@vinci.be",
  "password": "test123"
}

### Login member 2 (copy token into @token2)
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "email": "test2@vinci.be",
  "password": "test123"
}

### Read all notifications of a member
GET {{baseUrl}}/members/3/notifications
Authorization: Bearer {{token}}

### Read all notifications read of a member
GET {{baseUrl}}/members/3/notifications?read=true
Authorization: Bearer {{token}}

### Read all notifications unread of a member
GET {{baseUrl}}/members/3/notifications?read=false
Authorization: Bearer {{token}}

### Try to get notifications of a non-existent member (should return 404)
GET {{baseUrl}}/members/999/notifications
Authorization: Bearer {{token}}

### Try to get notifications of another member (should return 403)
GET {{baseUrl}}/members/1/notifications
Authorization: Bearer {{token2}}

### Send a notification to a member
POST {{baseUrl}}/members/1/notifications
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "type": "RESULT",
  "message": "Match gagné 3-1",
  "sendDate": "2026-03-05T12:30:00"
}

### Send a notification to a member
POST {{baseUrl}}/members/1/notifications
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "type": "RESULT",
  "message": "Match gagné 3-9",
  "sendDate": "2026-03-05T12:30:00"
}

### Try to send a notification with empty message (should fail 400)
POST {{baseUrl}}/members/1/notifications
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "type": "TOURNAMENT",
  "message": "",
  "sendDate": "2026-03-05T12:30:00"
}

### Try to send a notification to a non-existent member (should return 404)
POST {{baseUrl}}/members/999/notifications
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "type": "RESULT",
  "message": "Test membre inconnu",
  "sendDate": "2026-03-05T12:30:00"
}

### Try to send notification by another member (should return 403)
POST {{baseUrl}}/members/1/notifications
Content-Type: application/json
Authorization: Bearer {{token2}}

{
  "type": "RESULT",
  "message": "Tentative accès interdit",
  "sendDate": "2026-03-05T12:30:00"
}

### Mark a notification as read
PATCH {{baseUrl}}/members/1/notifications/1
Authorization: Bearer {{token}}

### Try to mark a non-existent notification (should return 404)
PATCH {{baseUrl}}/members/1/notifications/999
Authorization: Bearer {{token}}

### Try to mark notification by another member(should return 403)
PATCH {{baseUrl}}/members/1/notifications/1
Authorization: Bearer {{token2}}