@baseUrl = http://localhost:3000
@token =
### Register responsible member
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
  "email": "responsible@vinci.be",
  "password": "test123",
  "tag": "Responsible",
  "imageId": 1,
  "specialityId": 1
}

### Register regular member
POST {{baseUrl}}/auths/register
Content-Type: application/json

{
  "email": "member@vinci.be",
  "password": "test123",
  "tag": "Member",
  "imageId": 1,
  "specialityId": 1
}

### Login responsible (copy token into @token)
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "email": "responsible@vinci.be",
  "password": "test123"
}

### Login regular member (copy token into @token2)
POST {{baseUrl}}/auths/login
Content-Type: application/json

{
  "email": "member@vinci.be",
  "password": "test123"
}

### Create a team (valid, should return 201)
POST {{baseUrl}}/teams
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "MarouTeam"
}

### Try to create a team with empty name (should return 400)
POST {{baseUrl}}/teams
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": ""
}

### Try to create a team with same name (should return 409)
POST {{baseUrl}}/teams
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "MonEquipe"
}

### Try to create second team with same member (should return 409)
POST {{baseUrl}}/teams
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "AutreEquipe"
}



### Get team members (should return 200)
GET {{baseUrl}}/teams/members
Authorization: Bearer {{token}}

### Member without team (should return 404)
GET {{baseUrl}}/teams/members
Authorization: Bearer {{token}}

### No token (should return 401)
GET {{baseUrl}}/teams/members