@baseUrl = http://localhost:3000
@tokenResponsible = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhdXRoMCIsInVzZXJuYW1lIjoibWFuYWdlciIsImlhdCI6MTc3Mjk4NDI4MiwiZXhwIjoxNzczMDcwNjgyfQ.CaWuGQLW9547D2q65CVYE_74SuX8g3wlX0eETMt8uHE

### Validate result - success (should return 200)
POST {{baseUrl}}/matches/1/validate
Authorization: Bearer {{tokenResponsible}}

### Validate result - result not pending (should return 400)
POST {{baseUrl}}/matches/2/validate
Authorization: Bearer {{tokenResponsible}}

### Validate result - already responded (should return 400)
POST {{baseUrl}}/matches/3/validate
Authorization: Bearer {{tokenResponsible}}

### Validate result - match not found (should return 404)
POST {{baseUrl}}/matches/999/validate
Authorization: Bearer {{tokenResponsible}}

### Validate result - unauthorized (should return 403)
POST {{baseUrl}}/matches/1/validate
