<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://maven.apache.org/POM/4.0.0"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <artifactId>cae-exercices-demo</artifactId>
  <build>
    <plugins>
      <plugin>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <configuration>
          <excludes>
            <exclude>
              <artifactId>lombok</artifactId>
              <groupId>org.projectlombok</groupId>
            </exclude>
          </excludes>
        </configuration>
        <groupId>org.springframework.boot</groupId>
      </plugin>

      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <annotationProcessorPaths>
            <path>
              <artifactId>lombok</artifactId>
              <groupId>org.projectlombok</groupId>
              <version>1.18.34</version>
            </path>
          </annotationProcessorPaths>
          <compilerArgs>
            <arg>-parameters</arg>
          </compilerArgs>
          <source>21</source>
          <target>21</target>
        </configuration>
        <groupId>org.apache.maven.plugins</groupId>
        <version>3.8.1</version>
      </plugin>


      <plugin>
        <artifactId>maven-checkstyle-plugin</artifactId>
        <configuration>
          <configLocation>google_checks.xml</configLocation>
          <consoleOutput>true</consoleOutput>
          <failsOnError>true</failsOnError>
          <maxAllowedViolations>10</maxAllowedViolations>
          <violationSeverity>warning</violationSeverity>

        </configuration>
        <dependencies>
          <dependency>
            <artifactId>checkstyle</artifactId>
            <groupId>com.puppycrawl.tools</groupId>
            <version>10.20.0</version>
          </dependency>
        </dependencies>
        <executions>
          <execution>
            <goals>
              <goal>check</goal>
              <goal>checkstyle</goal>
            </goals>
            <phase>test</phase>
          </execution>
        </executions>
        <groupId>org.apache.maven.plugins</groupId>
        <version>3.6.0</version>
      </plugin>

      <plugin>
        <artifactId>maven-pmd-plugin</artifactId>
        <configuration>
          <failOnViolation>true</failOnViolation>
          <minimumTokens>40</minimumTokens>
          <printFailingErrors>true</printFailingErrors>
          <rulesets>
            <ruleset>rulesets/java/quickstart.xml</ruleset>
          </rulesets>
        </configuration>
        <executions>
          <execution>
            <configuration>
              <maxAllowedViolations>0</maxAllowedViolations>
            </configuration>
            <goals>
              <goal>check</goal>
            </goals>
            <id>pmd-check</id>
            <phase>test</phase>
          </execution>
          <execution>
            <configuration>
              <maxAllowedViolations>0</maxAllowedViolations>
            </configuration>
            <goals>
              <goal>cpd-check</goal>
            </goals>
            <id>pmd-cpd-check</id>
            <phase>test</phase>
          </execution>
        </executions>

        <groupId>org.apache.maven.plugins</groupId>
        <version>3.26.0</version>
      </plugin>

      <plugin>
        <artifactId>jacoco-maven-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>prepare-agent</goal>
            </goals>
          </execution>
          <execution>
            <goals>
              <goal>report</goal>
            </goals>
            <id>report</id>
            <phase>test</phase>
          </execution>
        </executions>
        <groupId>org.jacoco</groupId>
        <version>0.8.12</version>
      </plugin>


    </plugins>
  </build>
  <dependencies>
    <dependency>
      <artifactId>h2</artifactId>
      <groupId>com.h2database</groupId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <artifactId>spring-boot-starter-data-jpa</artifactId>
      <groupId>org.springframework.boot</groupId>
    </dependency>
    <dependency>
      <artifactId>spring-boot-starter-web</artifactId>
      <groupId>org.springframework.boot</groupId>
    </dependency>
    <dependency>
      <artifactId>spring-boot-starter-validation</artifactId>
      <groupId>org.springframework.boot</groupId>
    </dependency>
    <dependency>
      <artifactId>postgresql</artifactId>
      <groupId>org.postgresql</groupId>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <artifactId>lombok</artifactId>
      <groupId>org.projectlombok</groupId>
      <optional>true</optional>
    </dependency>
    <dependency>
      <artifactId>spring-boot-starter-test</artifactId>
      <groupId>org.springframework.boot</groupId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <artifactId>java-jwt</artifactId>
      <groupId>com.auth0</groupId>
      <version>4.4.0</version>
    </dependency>
    <dependency>
      <artifactId>spring-boot-starter-security</artifactId>
      <groupId>org.springframework.boot</groupId>
    </dependency>
    <dependency>
      <artifactId>spring-security-test</artifactId>
      <groupId>org.springframework.security</groupId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <artifactId>junit-jupiter</artifactId>
      <groupId>org.mockito</groupId>
      <version>2.20.0</version>
    </dependency>
  </dependencies>
  <description>auths</description>
  <groupId>be.vinci.ipl.cae.demos</groupId>
  <modelVersion>4.0.0</modelVersion>
  <name>auths</name>
  <parent>
    <artifactId>spring-boot-starter-parent</artifactId>
    <groupId>org.springframework.boot</groupId>
    <relativePath/>
    <version>3.3.4</version> <!-- lookup parent from repository -->
  </parent>
  <profiles>
    <profile>
      <build>
        <plugins>

          <plugin>
            <artifactId>maven-checkstyle-plugin</artifactId>
            <configuration>
              <consoleOutput>true</consoleOutput>
              <failOnViolation>false</failOnViolation>
              <failsOnError>false</failsOnError>
            </configuration>
            <groupId>org.apache.maven.plugins</groupId>
            <version>3.6.0</version>
          </plugin>

          <plugin>
            <artifactId>maven-pmd-plugin</artifactId>
            <executions>
              <execution>
                <configuration>
                  <failOnViolation>false</failOnViolation>
                </configuration>
                <goals>
                  <goal>check</goal>
                </goals>
                <id>pmd-check</id>
                <phase>test</phase>
              </execution>
              <execution>
                <configuration>
                  <failOnViolation>false</failOnViolation>
                </configuration>
                <goals>
                  <goal>cpd-check</goal>
                </goals>
                <id>pmd-cpd-check</id>
                <phase>test</phase>
              </execution>
            </executions>
            <groupId>org.apache.maven.plugins</groupId>

            <version>3.26.0</version>
          </plugin>

        </plugins>
      </build>
      <id>no-build-failure</id>
    </profile>
  </profiles>

  <properties>
    <java.version>21</java.version>
  </properties>

  <version>0.0.1-SNAPSHOT</version>

</project>
